#' Counts sequences in each assigned cluster
#'
#' @param list a list (in tibble format) generated by cluster_list_gen
#'
#' @return Generates a cluster count distribution table
#'
#' @import dplyr
#'
#' @export
#'
cluster_count_gen <- function(list){
list %>%
  group_by(cluster)%>%
  summarize(cluster_size=n()) %>%
  arrange(desc(cluster_size))
}
